/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_testndk_JNIStaticUtils */

#ifndef _Included_com_google_testndk_JNIStaticUtils
#define _Included_com_google_testndk_JNIStaticUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_testndk_JNIStaticUtils
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_google_testndk_JNIStaticUtils_getStringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
